version: "3"

services:
  app:
    build:
        context: .
        dockerfile: .docker/local/Dockerfile
    command:
      - /start
    ports:
        - 3000:3000
    volumes:
      - .:/home/node/app
      - ./.docker/local/zsh/.p10k.zsh:/home/node/.p10k.zsh:delegated
      - ./.docker/local/zsh/history:/home/node/zsh:delegated


